django_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls', namespace='music')),
]

music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # default home page for music. /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/album/add/
    # Call <class_name>.as_view() for doing a specific action (post)
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add')
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
# Define blueprints for database here.

# Each album has a unique primary key
class Album(models.Model):
    # Each variable represents a column in the database
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    # After a form submission, re-direct to the details page of the new album
    # Obtain the URL for a single model instance. Reverse() finds URL based on name
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    # String representation of object
    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    # Cascade means delete all other songs linked to album
    # An album can have multiple songs
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album

# Sync HTML views with models and database

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    # Default value is 'object_list'
    context_object_name = 'album_list'

    # Return all albums from database for index.html
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    # Object list name is model name by default
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    # Specify which fields the user can fill out
    fields = ['artist', 'album_title', 'genre', 'album_logo']
    # template_name is automatically <class_name>_form.html

music/templates/music/album_form.html
<!DOCTYPE html>
<html lang="en">
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}Active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- Import a form that allows the user to input album data -->
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</html>

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viber{% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href"{% static 'music/style.css' %}" />
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class-"container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
            </div>

        <!-- Items -->
            <!-- Collapse means hidden when there's not enough room on the screen -->
            <!-- Assigning topNavBar allows expansion of collapse-able elements -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <!-- Albums element -->
                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                        </a>
                    </li>
                    <!-- Music element -->
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Music
                        </a>
                    </li>
                </ul>

                <!-- Search element -->
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="query" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                        </a>
                    </li>
                       <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">

{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
    <img src="{{ album.album_logo }}">

    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>

    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img src="http://i.imgur.com/b9b13Rd.png"/>
        {% endif %}
        <br>
    {% endfor %}
{% endblock %}

</html>

music/templates/music/form-template.html
<!DOCTYPE html>
<html lang="en">
<!-- form contains all fields of album -->
{% for field in form %}
    <div class="form-group">
        <!-- If field value is invalid, produce an error message -->
        <div class="col-sm-offset-2 col-sm-19">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <!-- field name -->
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <!-- input field -->
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}
</html>

music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">

{% extends 'music/base.html' %}

{% block body %}
    <ul>
        {% for album in album_list %}
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

</html>